var rus = {
    foto: 'Фото',
    name: 'имя',
    tesak: 'Тип',
    gin: 'цена',
    or: 'день',
    patver: 'заказать',
    mutq: 'Вход',
    grancvel: 'регистрация',
    produ: 'Лист Продуктов',
    pntrel: 'поиск',
    zambyux: 'Корзина',
    chyntrel: 'Заказ отправлен',
    veradarnal: 'Вернутся к товаром',
    Quantity: 'Количество',
    Items: 'Цена продуктов',
    Total: 'Общая цена',
    View: 'Просмотр корзины',
    Update: 'Обновить Карзину',
    Order: 'Заказать',
    jnjel: 'Чтобы удалить продукт, установите его количество на 0.',
    empty: 'Ваша корзина пуста. Пожалуйста, добавьте несколько продуктов.',
    editpro: 'Изменить страницу',
    chanjpass: 'Изменить пароль',
    mypage: 'Моя страница ',
    myorder: 'Мои заказы',
    tesakani: 'Ассортимент',
    products: 'Продукты',
    grancvel: 'Регистрация',
    anun: 'Имя',
    azganun: 'Фамилия',
    heraxos: 'тел...',
    parol: 'Пароль',
    krknakiparol: 'Повторите пароль',
    irav: 'юридическое лицо',
    fiz: 'физическое лицо',
    durs: 'Выход',

};
var eng = {
    foto: 'photo',
    name: 'name',
    tesak: 'type',
    gin: 'price',
    or: 'days',
    patver: 'score',
    mutq: 'Login',
    grancvel: 'Registration',
    produ: 'Product List',
    pntrel: 'search',
    zambyux: 'Basket',
    chyntrel: 'You have not selected a product',
    yntrel: 'The order has been sent',
    veradarnal: 'Вack to the product',
    Quantity: 'Quantity',
    Items: 'Items Price',
    Total: 'Total Price',
    View: 'View cart',
    Update: 'Update cart',
    Order: 'Order',
    jnjel: 'To remove an item, set its quantity to 0. ',
    empty: 'Your Cart is empty. Please add some products.',
    editpro: 'Edit Profile',
    chanjpass: 'Change Password',
    mypage: 'My page',
    myorder: 'Мои заказы',
    myorder: 'My orders',
    tesakani: 'Assortment',
    products: 'Products',
    grancvel: 'Sign Up',
    anun: 'Name',
    azganun: 'Surname',
    heraxos: 'Tel...',
    parol: 'Password',
    krknakiparol: 'Confirm password',
    irav: 'Legal entity ',
    fiz: 'Individual person',
    durs: 'Logout',



};
var arm = {
    foto: 'Նկար',
    name: 'Անուն',
    tesak: 'Տեսակ',
    gin: 'Գին',
    or: 'Օր',
    patver: 'Պատվիրել',
    mutq: 'Մուտք',
    grancvel: 'Գրանցվել',
    produ: 'Ապրանքների ցուցակ',
    pntrel: 'փնտրել',
    zambyux: 'Զամբյուղ',
    chyntrel: 'Պատվերը կատարված է',
    veradarnal: 'Վերադառնալ ապրանքներին',
    Quantity: 'Քանակ',
    Items: 'Ապրանքների արժեք',
    Total: 'Ընդհանուր գումար',
    View: 'Զամբյուղի պարունակություն',
    Update: 'Թարմացնել զամբյուղը',
    Order: 'Պատվիրել',
    jnjel: 'Ապրանքը ջնջելու համար նրա քանակը դարձրեք 0',
    empty: 'Ձեր զամբյուղը դատարկ է: Խնդրում ենք ավելացնել որոշ ապրանքներ.',
    editpro: 'Փոփոել էջը',
    chanjpass: 'Փոխել գաղտնաբառը',
    mypage: 'Իմ էջ ',
    myorder: 'Իմ պատվերները',
    tesakani: 'Տեսականի',
    products: 'Ապրանքներ',
    grancvel: 'Գրանցվել',
    anun: 'Անուն',
    azganun: 'Ազգանուն',
    heraxos: 'Հեռ...',
    parol: 'Գաղտնաբառ',
    krknakiparol: 'Կրկնեք գաղտնաբառը',
    irav: 'Իրավաբանական անձ ',
    fiz: 'Ֆիզիկանական անձ',
    durs: 'Դուրս գալ',

};